name: Latest blog post workflow
on:
  schedule: # Run workflow automatically
    - cron: '0 0 * * 5' # Runs every Friday, at midnight
  push:
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme
jobs:
  update-readme-with-blog:
    name: Update README with latest feed posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Pull in my blog posts
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: 'BLOG-POSTS'
          commit_message: 'Updated README with the latest blog posts'
          feed_list: 'https://feeds.feedburner.com/x2od_wp'
          feed_names: 'X-Squared'
          template: '- [$title]($url)$newline'
          enable_keepalive: false
          tag_post_pre_newline: true
      - name: Pull RSS feed from Salesforce.Stackexchange
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: 'SalesforceStackexchange'
          commit_message: 'Updated README with the latest Salesforce.Stackexchange data'
          feed_list: 'https://salesforce.stackexchange.com/feeds/user/59'
          template: '- [$title]($url)$newline'
          enable_keepalive: true
          tag_post_pre_newline: true
          filter_comments: 'stackexchange/Comment by $author/'
